const DIRS={UP:[0,-1],DOWN:[0,1],LEFT:[-1,0],RIGHT:[1,0]},key=(x,y)=>`${x},${y}`,parts=()=>({food:0,escape:0,danger:0,revisit:0,time:0,completion:0});
export const DEFAULT_WEIGHTS=Object.freeze({food:1,targetFood:1,escape:1,danger:1,revisit:1,time:1,completion:1,foodBias:1,escapeBias:1,adjacentFood:1,pathGuide:1,repeatAvoidance:1});
export class MonteCarloPlanner{
  constructor(rng,{rollouts=96,depth=22,weights={}}={}){this.rng=rng;this.rollouts=rollouts;this.depth=depth;this.weights={...DEFAULT_WEIGHTS,...MonteCarloPlanner.activeWeights,...weights};this.transposition=new Map;this.cacheHits=0}
  recommend(engine,{targetKeys=new Set}={}){const root=engine.ontology,maze=root.query({type:'Maze'})[0],p=root.query({type:'Player'})[0],legal=this.legal(maze,p.x,p.y).map(x=>x.direction),rootKey=this.worldKey(root),prior=this.transposition.get(rootKey),stats=new Map(legal.map(d=>{const old=prior?.[d];if(old){this.cacheHits++;const n=Math.min(old.visits,12),components=Object.fromEntries(Object.entries(old.average||parts()).map(([k,v])=>[k,v*n]));return[d,{direction:d,visits:n,total:old.mean*n,safe:old.safety*n,collisions:(1-old.safety)*n,best:old.best,outcomes:old.outcomes.slice(-12),components}]}return[d,{direction:d,visits:0,total:0,safe:0,collisions:0,best:-Infinity,outcomes:[],components:parts()}]})),trail=[];
    for(let i=0;i<this.rollouts;i++){const unexplored=legal.find(d=>!stats.get(d).visits),direction=unexplored||this.selectUCB(stats,i+1),world=root.clone({includeEvents:false,shareTypes:['Maze','TopologyModel','JunctionNetwork','CorridorNetwork','BottleneckSet','Zone']}),result=this.rollout(world,direction,targetKeys),s=stats.get(direction);s.visits++;s.total+=result.reward;s.outcomes.push(result.reward);s.safe+=result.safe?1:0;s.collisions+=result.safe?0:1;s.best=Math.max(s.best,result.reward);for(const k of Object.keys(s.components))s.components[k]+=result.components[k];if(i<12||i%8===7||i===this.rollouts-1)trail.push({iteration:i+1,chosen:direction,reward:result.reward,leader:this.leader(stats)})}
    const plans=[...stats.values()].map(s=>({...s,score:s.total/s.visits,cvar:this.cvar(s.outcomes,.2),safety:s.safe/s.visits,confidence:s.visits/(this.rollouts+(prior?Math.min(12,s.visits):0)),average:Object.fromEntries(Object.entries(s.components).map(([k,v])=>[k,v/s.visits]))})).sort((a,b)=>b.safety-a.safety||b.cvar-a.cvar||b.score-a.score),explanation=this.explain(plans[0],plans[1]);this.transposition.set(rootKey,Object.fromEntries(plans.map(p=>[p.direction,{visits:p.visits,mean:p.score,safety:p.safety,best:p.best,outcomes:p.outcomes.slice(-20),average:p.average}])));if(this.transposition.size>400)this.transposition.delete(this.transposition.keys().next().value);return{direction:plans[0]?.direction||legal[0],plans,trail,simulations:this.rollouts,depth:this.depth,explanation,cacheHits:this.cacheHits,tableSize:this.transposition.size}}
  worldKey(world){const p=world.query({type:'Player'})[0],g=world.query({type:'Ghost'}).map(x=>`${x.x},${x.y}`).join('|'),foods=world.query({where:o=>o.type==='Pellet'||o.type==='PowerPellet'});let hash=2166136261;for(const f of foods){hash^=(f.x*31+f.y);hash=Math.imul(hash,16777619)}return`${p.x},${p.y}/${g}/${foods.length}/${hash>>>0}`}
  legal(maze,x,y){return Object.entries(DIRS).filter(([, [dx,dy]])=>maze.grid[y+dy]?.[x+dx]===0).map(([direction,[dx,dy]])=>({direction,x:x+dx,y:y+dy}))}
  selectUCB(stats,total){return[...stats.values()].sort((a,b)=>this.ucb(b,total)-this.ucb(a,total))[0].direction}
  ucb(s,total){const collisionRisk=s.collisions/s.visits;return s.total/s.visits-collisionRisk*250000+2.1*Math.sqrt(Math.log(total)/s.visits)}
  cvar(outcomes,ratio){const sorted=[...outcomes].sort((a,b)=>a-b),n=Math.max(1,Math.ceil(sorted.length*ratio));return sorted.slice(0,n).reduce((a,b)=>a+b,0)/n}
  leader(stats){return[...stats.values()].filter(s=>s.visits).sort((a,b)=>b.safe/b.visits-a.safe/a.visits||b.total/b.visits-a.total/a.visits)[0]?.direction||'—'}
  explain(best,next){if(!best)return'이동 가능한 방향이 없습니다.';const a=best.average,why=[];if(best.safety===1)why.push('모든 표본에서 충돌 없음');else why.push(`생존율 ${(best.safety*100).toFixed(0)}%`);why.push(`최악 20% 기대값 ${best.cvar.toFixed(0)}`);if(a.food>Math.max(8,Math.abs(a.escape)))why.push('먹이 획득 효율 우세');if(a.escape>8)why.push('고스트와 거리 확보');const gap=next?`차선보다 CVaR ${(best.cvar-next.cvar).toFixed(0)}, 평균 ${(best.score-next.score).toFixed(0)} 우세`:'유일한 이동 방향';return`${best.direction} 선택: ${why.join(' · ')}. ${gap}.`}
  rollout(world,firstDirection,targetKeys){const maze=world.query({type:'Maze'})[0],player=world.query({type:'Player'})[0],ghosts=world.query({type:'Ghost'}).map(g=>({...g})),foods=new Set(world.query({where:o=>o.type==='Pellet'||o.type==='PowerPellet'}).map(f=>key(f.x,f.y)));let px=player.x,py=player.y,direction=firstDirection,reward=0,visited=new Map,components=parts();
    for(let depth=0;depth<this.depth;depth++){const oldP={x:px,y:py},oldGhosts=ghosts.map(g=>({x:g.x,y:g.y})),[dx,dy]=DIRS[direction];px+=dx;py+=dy;const ghostNext=ghosts.map(g=>this.simulateGhostMove(maze,g,oldP));for(let i=0;i<ghosts.length;i++){ghosts[i].x=ghostNext[i].x;ghosts[i].y=ghostNext[i].y}const collision=ghosts.some((g,i)=>g.x===px&&g.y===py||oldGhosts[i].x===px&&oldGhosts[i].y===py&&g.x===oldP.x&&g.y===oldP.y);if(collision)return{reward:-1000000-depth*1000,safe:false,components};const time=-2*this.weights.time;reward+=time;components.time+=time;
      const k=key(px,py);visited.set(k,(visited.get(k)||0)+1);if(foods.delete(k)){const v=40*this.weights.food+(this.depth-depth)*3*this.weights.food+(targetKeys.has(k)?35*this.weights.targetFood:0);reward+=v;components.food+=v}if(!foods.size){const v=(2000-depth*20)*this.weights.completion;components.completion+=v;return{reward:reward+v,safe:true,components}}const oldNear=Math.min(...oldGhosts.map(g=>Math.abs(g.x-oldP.x)+Math.abs(g.y-oldP.y))),near=Math.min(...ghosts.map(g=>Math.abs(g.x-px)+Math.abs(g.y-py)));if(near<=5){const escape=(near-oldNear)*32*this.weights.escape,danger=-Math.pow(6-near,2)*9*this.weights.danger;reward+=escape+danger;components.escape+=escape;components.danger+=danger}const revisit=-(visited.get(k)-1)*9*this.weights.revisit;reward+=revisit;components.revisit+=revisit;
      const moves=this.legal(maze,px,py);if(!moves.length)break;const weighted=moves.map(m=>{const futureNear=Math.min(...ghosts.map(g=>Math.abs(g.x-m.x)+Math.abs(g.y-m.y))),escape=near<=5?(futureNear-near)*12*this.weights.escapeBias:0;return{value:m.direction,weight:Math.max(.05,1+(foods.has(key(m.x,m.y))?9*this.weights.foodBias:0)+escape+futureNear*.8-(visited.get(key(m.x,m.y))||0)*3*this.weights.revisit)}});direction=this.rng.pickWeighted(weighted)}const remaining=-foods.size*.08*this.weights.food;return{reward:reward+remaining,safe:true,components}}
  simulateGhostMove(maze,ghost,player){const moves=this.legal(maze,ghost.x,ghost.y);if(!moves.length)return{x:ghost.x,y:ghost.y};return this.rng.pickWeighted(moves.map(m=>({value:m,weight:Math.exp(-(Math.abs(m.x-player.x)+Math.abs(m.y-player.y))*.48)+.12})))}
}
