import{MazeTopologyIndex}from'./MazeTopologyIndex.js';
const MOVES=[[1,0],[-1,0],[0,1],[0,-1]],key=(x,y)=>`${x},${y}`;
export class SemanticAnalysisService{
  install(ontology,maze){const topology=new MazeTopologyIndex().build(maze);ontology.createObject('TopologyModel',{...topology},'topology');ontology.createRelationship('describes','topology','maze');ontology.createObject('JunctionNetwork',{count:topology.counts.junctions},'junction-network');ontology.createObject('CorridorNetwork',{count:topology.counts.corridors},'corridor-network');ontology.createObject('BottleneckSet',{count:topology.counts.bottlenecks},'bottleneck-set');ontology.createRelationship('contains','topology','junction-network');ontology.createRelationship('contains','topology','corridor-network');ontology.createRelationship('contains','topology','bottleneck-set');for(const z of topology.zones)ontology.createObject('Zone',{size:z.size,cellKeys:z.cells.map(c=>key(c.x,c.y))},z.id);for(const z of topology.zones)ontology.createRelationship('contains','topology',z.id);ontology.createObject('ThreatField',{tick:-1,ghostArrival:{},playerArrival:{},safetyMargin:{},safeCellCount:0,safeZoneCount:0},'threat-field');ontology.createObject('SafeZoneSummary',{count:0,largestSize:0},'safe-zone-summary');ontology.createObject('EscapeRouteSummary',{count:0},'escape-route-summary');ontology.createObject('FoodClusterSummary',{count:0,remainingFood:0},'food-cluster-summary');ontology.createRelationship('derivedFrom','threat-field','maze');ontology.createRelationship('produces','threat-field','safe-zone-summary');ontology.createRelationship('produces','threat-field','escape-route-summary');ontology.createRelationship('informs','threat-field','food-cluster-summary');return topology}
  update(ontology,tick){const maze=ontology.query({type:'Maze'})[0],player=ontology.query({type:'Player'})[0],ghosts=ontology.query({type:'Ghost'}),ghostArrival=this.multiSourceDistance(maze,ghosts),playerArrival=this.multiSourceDistance(maze,[player]),safetyMargin={},ghostReachableSets=this.reachableSets(maze,ghosts,Math.min(12,6+ghosts.length));let safeCellCount=0;for(const[k,pd]of Object.entries(playerArrival)){const margin=(ghostArrival[k]??999)-pd;safetyMargin[k]=margin;if(margin>1)safeCellCount++}const safeZones=this.safeComponents(maze,safetyMargin),field=ontology.objects.get('threat-field');Object.assign(field,{tick,ghostArrival,playerArrival,safetyMargin,ghostReachableSets,safeCellCount,safeZoneCount:safeZones.length,minPlayerMargin:safetyMargin[key(player.x,player.y)]??0});const summary=ontology.objects.get('safe-zone-summary');Object.assign(summary,{count:safeZones.length,largestSize:Math.max(0,...safeZones.map(z=>z.length)),tick});const escape=ontology.objects.get('escape-route-summary'),topology=ontology.objects.get('topology'),nearSafeJunctions=topology.junctions.filter(j=>(safetyMargin[key(j.x,j.y)]??-99)>1).length;Object.assign(escape,{count:nearSafeJunctions,tick});const foods=ontology.query({where:o=>o.type==='Pellet'||o.type==='PowerPellet'}),clusters=new Set(foods.map(f=>`${Math.floor(f.x/5)},${Math.floor(f.y/5)}`));Object.assign(ontology.objects.get('food-cluster-summary'),{count:clusters.size,remainingFood:foods.length,tick});return field}
  reachableSets(maze,sources,horizon){let frontier=new Set(sources.map(s=>key(s.x,s.y))),reachable=new Set(frontier),sets=[...Array(horizon+1)];sets[0]=[...frontier];for(let t=1;t<=horizon;t++){const next=new Set;for(const k of frontier){const[x,y]=k.split(',').map(Number);for(const[dx,dy]of MOVES)if(maze.grid[y+dy]?.[x+dx]===0)next.add(key(x+dx,y+dy))}for(const k of next)reachable.add(k);sets[t]=[...reachable];frontier=next}return sets}
  multiSourceDistance(maze,sources){const dist={},q=[];for(const s of sources){const k=key(s.x,s.y);if(dist[k]!==undefined)continue;dist[k]=0;q.push({x:s.x,y:s.y})}for(let i=0;i<q.length;i++){const p=q[i],d=dist[key(p.x,p.y)];for(const[dx,dy]of MOVES){const x=p.x+dx,y=p.y+dy,k=key(x,y);if(maze.grid[y]?.[x]!==0||dist[k]!==undefined)continue;dist[k]=d+1;q.push({x,y})}}return dist}
  safeComponents(maze,margins){const safe=new Set(Object.keys(margins).filter(k=>margins[k]>1)),seen=new Set,out=[];for(const start of safe)if(!seen.has(start)){const q=[start],group=[];seen.add(start);for(let i=0;i<q.length;i++){const k=q[i],[x,y]=k.split(',').map(Number);group.push(k);for(const[dx,dy]of MOVES){const nk=key(x+dx,y+dy);if(safe.has(nk)&&!seen.has(nk)){seen.add(nk);q.push(nk)}}}out.push(group)}return out}
}
